title: Fontra Docs
email: gustavo@hipertipo.com
description: Fontra user documentation
baseurl: ""
# url: https://gferreira.github.io/fontra-docs
url: https://hipertipo.gitlab.io/fontra-docs

markdown: kramdown

version: 0.1

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

jekyll_tidy:
  exclude: []
  # ignore_env: development
  compress_html: false
